# Generated by Django 2.1.2 on 2018-12-04 11:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gameMul', models.FloatField(default=2)),
                ('gameDiv', models.FloatField(default=3)),
                ('gameMin', models.IntegerField(default=1)),
                ('gameMax', models.IntegerField(default=100)),
                ('gameStart', models.DateTimeField()),
                ('gameEnd', models.DateTimeField()),
            ],
        ),
    ]
