# Generated by Django 2.1.2 on 2018-12-05 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamerooms', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameroom',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gamerooms.Gameroom'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['gameroom'], name='games_game_gameroo_2f2bb4_idx'),
        ),
    ]
