# Generated by Django 2.1.2 on 2018-12-03 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='guess',
            index=models.Index(fields=['game'], name='guesses_gue_game_id_733ba5_idx'),
        ),
        migrations.AddIndex(
            model_name='guess',
            index=models.Index(fields=['user'], name='guesses_gue_user_id_e0f173_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='guess',
            unique_together={('game', 'user')},
        ),
    ]
